CREATE TABLE posts (
   id INT AUTO_INCREMENT PRIMARY KEY,
   titulo VARCHAR(255) NOT NULL,
   slug VARCHAR(255) UNIQUE NOT NULL,
   conteudo TEXT NOT NULL,
   autor VARCHAR(100),
   criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
   atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
